# Generated by Django 5.0.3 on 2024-04-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill_blank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('question', models.CharField(max_length=255)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='paragraph',
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
