# Generated by Django 5.0.3 on 2024-04-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_rename_publicusers_publicuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='publicuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
